development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dev-todo-on-rails
  pool: 5
  username: leoo
  password: leoomysql
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test-todo-on-rails
  pool: 5
  username: leoo
  password: leoomysql
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todo-on-rails
  pool: 5
  username: leoo
  password: leoomysql
  host: localhost
